sonar.projectKey=sre-alerts
sonar.projectName=sre-alerts
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/*.min.js,**/*.min.css,**/node_modules/**,**/.git/**,**/dist/**,**/build/**,**/__pycache__/**,**/*.pyc,**/vendor/**

sonar.host.url=https://sonarqube.vforeseetech.com
